name: Compile latex to PDF

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  compile_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: LaTeX compilation
      uses: dante-ev/latex-action@2021-A
      with:
        root_file: appunti-analisi.tex
        working_directory: .
        compiler: latexmk
        args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: appunti-analisi.pdf
